name: Upload to CDN

on:
  push:
    branches:
      - master
      
  workflow_dispatch:

permissions:
  contents: 'read'
  id-token: 'write'

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 #v4.1.7
      
      - id: 'auth'
        name: 'GCP Auth'
        uses: 'google-github-actions/auth@62cf5bd3e4211a0a0b51f2c6d6a37129d828611d' #v2.1.5
        with:
          workload_identity_provider: ${{ secrets.GH_ACTIONS_CDN_WIP }}
          service_account: ${{ secrets.GH_ACTIONS_CDN_SA }}

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@f0990588f1e5b5af6827153b93673613abdc6ec7' #v2.1.1

      - name: Change folder names to lowercase
        run: |
          find ronin/* -maxdepth 2 -type d -exec sh -c 'mv "$1" "$(dirname "$1")/$(basename "$1" | tr "[:upper:]" "[:lower:]")"' _ {} \;  

      - name: 'Upload CDN'
        run: |
          set -eo pipefail
          gsutil -m rsync -d -r -x '^(?!ronin/).*' ./ gs://${{ vars.CDN_BUCKET_NAME }}
